config/routes.rb
LinkBlog::Application.routes.draw do
  root :to => 'links#index'

  resources :links

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :URL, :date_found

  validates :URL, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def index
		@links = Link.all
	end

	def new
		@link = Link.new(params[:link])
		@link.save
	end

	def create
		@link = Link.new(params[:link])
		if @link.save
			flash[:notice] = "Link has been created."
			redirect_to @link
		else
			flash[:alert] = "Link has not been created."
			render :action => "new"
		end
	end

	def show
		@link = Link.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "LinkBlog").join(" - ")
			end
		end
	end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if content_for?(:title) %>
  		<%= yield(:title) %>
  	<% else %>
  		LinkBlog
		<% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<div class="flash" id="<%= key %>">
		<%= value %>
	</div>	
<% end %>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<%= link_to "New Link", new_link_path  %>
<ul>
	<% @links.sort! { |a,b| b.created_at <=> a.created_at } %>
	<% @links.each do |link| %>
		<li><%= link_to link.URL, link %></li>	
	<% end %>
</ul>

app/views/links/new.html.erb
<h2>New Link</h2>

<%= form_for(@link) do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :URL %> <br />
		<%= f.text_field :URL %>
	</p>

	<p>
		<%= f.label :date_found %> <br />
		<%= f.text_field :date_found %>
	</p>
	<%= f.submit %>
	
<% end  %>

app/views/links/show.html.erb
<% title(@link.URL, "Links") %>
<h2><%= @link.URL %></h2>